// Auth
export const SET_IS_AUTH_LOADING = 'SET_IS_AUTH_LOADING';
export const SET_IS_CONFIRM_LOADING = 'SET_IS_CONFIRM_LOADING';
export const SET_IS_ADDITIONAL_INFO_LOADING =
	'SET_IS_SET_IS_ADDITIONAL_INFO_LOADING_INFO_LOADING';
export const SET_CONFIRMATION = 'SET_CONFIRMATION';
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';

// Contacts
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const SET_IS_CONTACTS_LOADING = 'SET_IS_CONTACTS_LOADING';
export const SET_IS_CONTACTS_MULTI_SELECT = 'SET_IS_CONTACTS_MULTI_SELECT';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const DESELECT_CONTACT = 'DESELECT_CONTACT';
export const CLEAR_SELECTED_CONTACTS = 'CLEAR_SELECTED_CONTACTS';
export const ADD_TO_SEARCH_RESULT = 'ADD_TO_SEARCH_RESULT';
export const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT';

// Favorite Contacts
export const ADD_TO_FAVORITE_CONTACTS = 'ADD_TO_FAVORITE_CONTACTS';
export const REMOVE_FROM_FAVORITE_CONTACTS = 'REMOVE_FROM_FAVORITE_CONTACTS';
export const REMOVE_ALL_FAVORITE_CONTACTS = 'REMOVE_ALL_FAVORITE_CONTACTS';
export const SET_IS_FAVORITES_MULTI_SELECT = 'SET_IS_FAVORITES_MULTI_SELECT';
export const SELECT_FAVORITE_CONTACT = 'SELECT_FAVORITE_CONTACT';
export const DESELECT_FAVORITE_CONTACT = 'DESELECT_FAVORITE_CONTACT';
export const CLEAR_SELECTED_FAVORITE_CONTACTS =
	'CLEAR_SELECTED_FAVORITE_CONTACTS';
export const ADD_TO_FAVORITE_SEARCH_RESULT = 'ADD_TO_FAVORITE_SEARCH_RESULT';
export const CLEAR_FAVORITE_SEARCH_RESULT = 'CLEAR_FAVORITE_SEARCH_RESULT';
