// Auth
export const SET_IS_AUTH_LOADING = 'SET_IS_AUTH_LOADING';
export const SET_IS_CONFIRM_LOADING = 'SET_IS_CONFIRM_LOADING';
export const SET_IS_ADDITIONAL_INFO_LOADING =
	'SET_IS_SET_IS_ADDITIONAL_INFO_LOADING_INFO_LOADING';
export const SET_CONFIRMATION = 'SET_CONFIRMATION';
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';
